# Generated by Django 3.1.7 on 2021-04-20 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellidoPaterno', models.CharField(max_length=255)),
                ('apellidoMaterno', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField()),
                ('acciones_tomadas', models.CharField(max_length=255)),
                ('estatus', models.BooleanField()),
                ('reporto_persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidentes.persona')),
            ],
        ),
    ]
