# Generated by Django 3.1.7 on 2021-04-20 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0003_auto_20210420_0605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidente',
            name='acciones_tomadas',
        ),
    ]
