# Generated by Django 3.1.7 on 2021-04-22 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0004_remove_incidente_acciones_tomadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidente',
            name='razon_de_cambio',
            field=models.CharField(default='def', max_length=255),
            preserve_default=False,
        ),
    ]
